# 기본 환경 설정
server:
  port: 80

decorator:
  datasource:
    p6spy:
      enable-logging: true # 쿼리 파라미터 바인딩 로그

# 프로퍼티 설정
my:
  nickname: cjh

spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100 #지연 로딩 최적화, 100 ~ 1000 사이로 추천
#  data:
#    web:
#      pageable:
#        one-indexed-parameters: true # 페이지 번호 1부터 시작
